POSITION:
  XOFFSET: 200
  YOFFSET: 100
  W: 1920
  H: 1080
BACKGROUND:
  COLOR: [255,255,230,255]
  LINE_COLOR: [180, 180, 180, 150]
  GRID_SIZE: 160
  ZOOM_FACTOR: 1.1
  ZOOM_UPPER: 1.3
  ZOOM_LOWER: 0.3
NODE:
  BASE_WIDTH: 200
  BASE_HEIGHT: 200
  BACKGROUND:
    COLOR: [230, 230, 230, 255]
  BORDER:
    WIDTH: 2
    RADIUS: 10
    COLOR: [100, 100, 100, 255]
    COLOR_SELECTED: [178, 80, 80, 250]
  TITLE:
    TEXT_COLOR: [255,255,255,255]
    BACKGROUND_COLOR: [68,114,196,255]
    FONT_SIZE: 18
  TEXT:
    TEXT_COLOR: [25,70,159,255]
    FONT_SIZE: 11
SLOT: 
  PAD_LEFT: 14
  PAD_RIGHT: 21
  MARGIN_TITLE: 5
  CIRCLE:
    COLOR: [25,60,90,255]
    RADIUS: 12
    INTERVAL: 30
  TEXT:
    SIZE: 10
    WEIGHT: 15
    PAD_TOP: 2
    PAD_SIDE: 5
CONNECTION:
  WIDTH: 4